version: 2
updates:
  # Maintain Cargo dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
